#!/usr/bin/python

CONST_COUNTIES = [ 'Atlantic', 
                   'Bergen', 
                   'Burlington', 
                   'Camden', 
                   'Cape May', 
                   'Cumberland', 
                   'Essex', 
                   'Gloucester', 
                   'Hudson', 
                   'Hunterdon', 
                   'Mercer', 
                   'Middlesex', 
                   'Monmouth', 
                   'Morris', 
                   'Ocean', 
                   'Passaic', 
                   'Salem', 
                   'Somerset', 
                   'Sussex', 
                   'Union', 
                   'Warren' ]

CONST_OFFICES = [ 'President',
                  'U.S. House',
                  'State Senate',
                  'General Assembly' ]

CONST_FEDERAL_DISTRICTS = [ "1", 
                            "2",
                            "3",
                            "4",
                            "5",
                            "6",
                            "7",
                            "8",
                            "9",
                            "10",
                            "11",
                            "12" ]

CONST_STATE_DISTRICTS = [ "1", 
                          "2",
                          "3",
                          "4",
                          "5",
                          "6",
                          "7",
                          "8",
                          "9",
                          "10",
                          "11",
                          "12",
                          "13",
                          "14",
                          "15",
                          "16",
                          "17",
                          "18",
                          "19",
                          "20",
                          "21",
                          "22",
                          "23",
                          "24",
                          "25",
                          "26",
                          "27",
                          "28",
                          "29",
                          "30",
                          "31",
                          "32",
                          "33",
                          "34",
                          "35",
                          "36",
                          "37",
                          "38",
                          "39",
                          "40" ]
